### PR TITLE
Fix file name

### PR DESCRIPTION
**Pull request by rashanjyot**
Corrected file name.

### CODE REVIEW

**Comment by rashanjyot** [comment]
Hey, @Miladinho can you please review this?

**Comment by rashanjyot** [comment]
Hey, @SebastianAigner can you please review this?

**Comment by rashanjyot** [comment]
Hey, @SebastianAigner I've fixed a typo here?

**Comment by SebastianAigner** [comment]
Yup, looks good to me. Merging :)

**Pull request merged**
